### PR TITLE
Keras nlp fixes

### PR DESCRIPTION
**Pull request by walteriviera**
- Added "statichmethod" to solve positionl argument compatibility issue from py36 to py39
- Fixed error rised by multiple inputs in the model

### CODE REVIEW

**Comment by openfl-helper** [comment]
Can one of the admins verify this patch?

**Comment by psfoley** [comment]
Hey @walteriviera, thanks for the contribution! Could you please rebase from the `1.1` tag onto `intel:develop`?

**Comment by itrushkin** [comment]
ok to test

**Comment by walteriviera** [comment]
Hi Patrick,

knowing that I cannot trust my github skills, I re-cloned the repo and moved into develop, fetched it, created a new branch and committed the few changes. You should be able to see a new PR now. I hope it works, in case, just let me know.

Thanks for the patience and apologies for these issues.

Walter Riviera - Intel Corp
DCG Sales - AI Technical Solution Specialist

**Pull request closed without merging**
