### PR TITLE
added encoding=utf8

### PR DESCRIPTION
**Pull request by lesliewubbel**

### CODE REVIEW

**Comment by MasterSkepticista** [comment]
@Gresliebear Could you please sign the CLA?
@acharyasunil Can you do a quick check if this fix works on Windows and Linux (with a clean venv)?

**Comment by lesliewubbel** [comment]
recheck

**Comment by lesliewubbel** [comment]
> @Gresliebear Could you please sign the CLA? @acharyasunil Can you do a quick check if this fix works on Windows and Linux (with a clean venv)?

Sorry MasterSkepticista this is my first PR I don't how to sign this CLA do I type something into commet and it reads it?

**Comment by MasterSkepticista** [comment]
@Gresliebear You can add a new comment with this line: 

*I have read the CLA Document and I hereby sign the CLA*

**Comment by lesliewubbel** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sun1lach** [comment]
@MasterSkepticista 
README.me UTF-8 Encoding works fine on Windows & Linux.

**Pull request merged**
