### PR TITLE
Formatting for entire `openfl` namespace (including experimental)

### PR DESCRIPTION
**Pull request by MasterSkepticista**
Pylint score before any changes: **5.45/10**
Edit: Pylint score after this PR: **8.09/10**

- [x] Convert all imports to be absolute.
- [x] Migrate all imports to be on top-level.
- [x] Sort all imports.
- [x] Re-insert updated `Copyright` headers in all impacted files.
- [x] Update Github actions workflow to use the new linting script.
- [x] Format code.
- [x] Clear all CI tests.
- [x] Works with OpenFL-Security.

Reviewers, pls note: https://github.com/securefederatedai/openfl/blob/ac3ed37f13c8f8e1e9f7dd8f355545f6069d93c1/tests/openfl/interface/test_aggregator_api.py#L70-L77

### CODE REVIEW

**Comment by MasterSkepticista** [comment]
This has been a tiring one. Request this be merged as soon as we can (ideally before any open feature PRs), so future PRs can make use of the updated code practices.

**Review by mansishr — APPROVED** [review]
LGTM! Great work!

**Review by kminhta — APPROVED** [review]
LGTM! Thanks for the effort. Code looks much cleaner now. This will be nice going forward

**Review by nammbash — APPROVED** [review]
Nice technical debt PR!. LGTM

**Review by psfoley — APPROVED** [review]
Great work, @MasterSkepticista! Approved and ready for merge

**Pull request merged**
