### PR TITLE
adding bandit tool

### PR DESCRIPTION
**Pull request by rajithkrishnegowda**
To enhance the security posture of our software development lifecycle, we are introducing Bandit, a popular security analysis tool specifically designed for Python applications.

Key Reasons for Adding Bandit:

1. Static Analysis for Security Vulnerabilities
2. Early Detection
3. Compliance and Best Practices
4. Automated Security Audits

Results 
https://github.com/securefederatedai/openfl/actions/runs/11049131910

[bandit-results.zip](https://github.com/user-attachments/files/17145925/bandit-results.zip)

### CODE REVIEW

**Comment by MasterSkepticista** [comment]
Where will the scan results persist?

**Comment by rajithkrishnegowda** [comment]
> Where will the scan results persist?

After the Bandit scan runs successfully, the results are uploaded as an artifact in the GitHub Actions workflow as bandit-results.json file. You can access them by following these steps:

1. Navigate to the Actions Tab: Go to the "Actions" tab of your GitHub repository.
2. Select the Latest Workflow Run: Click on the specific run for your Bandit workflow.
3. Download Artifacts: At the bottom of the workflow run details, you will find an "Artifacts" section. The Bandit results will be listed there as bandit-results. You can download the bandit-results.zip file from this section which contains json file.

**Review by MasterSkepticista — APPROVED** [review]

**Comment by MasterSkepticista** [comment]
GaNDLF test is failing on all new PRs. I suspect broken requirements

**Review by rahulga1 — APPROVED** [review]

**Comment by rajithkrishnegowda** [comment]
Bandit tool is not approved by intel. hence closing this PR

**Pull request closed without merging**
