### PR TITLE
Added citation

### PR DESCRIPTION
**Pull request by sarthakpati**
Addressing comments from #77

### CODE REVIEW

**Comment by openfl-helper** [comment]
Can one of the admins verify this patch?

**Comment by sarthakpati** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sarthakpati** [comment]
recheck

**Comment by alexey-gruzdev** [comment]
@sarthakpati I removed `azure-pipelines.yaml` since this is not related to citation part(so, I believe we need further discussion on that) and after that it can be merged via separate PR.

**Pull request merged**
