### PR TITLE
Removing the Python Native API

### PR DESCRIPTION
**Pull request by tanwarsh**
Deprecate Python API:

1. Mark Python native API as deprecated in the doc
2. Remove Python native API code.
3. Remove github workflow realted code.
4. Remove test related to Python native API.
5. Remove Tutorials related to Python native API.

This PR will be merged after discussion on FETS Chanllenge as mentioned by Kevin in https://github.com/securefederatedai/openfl/pull/1143#issuecomment-2476567671

### CODE REVIEW

**Comment by tanwarsh** [comment]
@teoparvanov @vrancurel I can still see pipelines and code related to interactive API. Will this be removed?
These 3 pipelines are failing as these interactive api code is using python native API.
eg code in openfl/openfl/interface/interactive_api/*

**Comment by teoparvanov** [comment]
> @teoparvanov @vrancurel I can still see pipelines and code related to interactive API. Will this be removed? These 3 pipelines are failing as these interactive api code is using python native API. eg code in openfl/openfl/interface/interactive_api/*

Hi @tanwarsh, thanks for refreshing the PR. Could you please remove the failing Interactive API examples from the CI also?

**Comment by tanwarsh** [comment]
> > @teoparvanov @vrancurel I can still see pipelines and code related to interactive API. Will this be removed? These 3 pipelines are failing as these interactive api code is using python native API. eg code in openfl/openfl/interface/interactive_api/*
> 
> Hi @tanwarsh, thanks for refreshing the PR. Could you please remove the failing Interactive API examples from the CI also?

I have removed the dependency on python native API in openfl/openfl/interface/interactive_api.

**Comment by teoparvanov** [comment]
Thanks @tanwarsh ! Let's freeze this PR for the time of the 1.7 release (we now have a good understanding of the "blast radius" of removing the Python Native API). 

As discussed offline, the next step is to produce a new, more conservative PR where you would:
- mark the Python Native API as deprecated in all docs
- move the tutorials based on this API under `deprecated/native_api`

**Comment by tanwarsh** [comment]
Closing the PR as this will be merged later. Will create another PR to deprecate Python Native API.

**Pull request closed without merging**
