### PR TITLE
Fix for tensor_db get_aggregated_tensor returns tuple in corner case 1087

### PR DESCRIPTION
**Pull request by tanwarsh**
Describe the bug
Calling get_aggregated_tensor on a tensor that has already been aggregated returns a tuple of (tensor, {}).

For more information please refer https://github.com/securefederatedai/openfl/issues/1087

Reproduced by  calling get_aggregated_tensor twice from aggregator while running experiment with 2 collaborators.

Before:
Screenshot 2024-11-05 at 4 54 49 PM

After:
Screenshot 2024-11-05 at 5 02 02 PM

### CODE REVIEW

**Review by rahulga1 — APPROVED** [review]

**Comment by scngupta** [comment]
My **impression** was that this scenario: aggregator calling get_aggregated_tensor on a tensor that has already been aggregated should not occur in **normal conditions.** For e.g. this may happen when there is an undesired behavior due to which aggregator is performing the aggregation twice. In this case I found that the existing functionality of returning a tuple + subsequent exception actually helps catch undesired behavior in the system 

Can you please clarify if there are use cases where this is an intended behavior?

**Comment by scngupta-dsp** [comment]
My **impression** was that this scenario: aggregator calling get_aggregated_tensor on a tensor that has already been aggregated should not occur in **normal conditions**. For e.g. this may happen when there is an undesired behavior due to which aggregator is performing the aggregation twice. In this case I found that the existing functionality of returning a tuple + subsequent exception actually helps catch undesired behavior in the system

Can you please clarify if there are use cases where this is an intended behavior ?

**Review by nisha987 — APPROVED** [review]

**Comment by MasterSkepticista** [comment]
@tanwarsh Could you provide a MWE for this bug?

**Comment by teoparvanov** [comment]
Closing this PR following https://github.com/securefederatedai/openfl/issues/1087#issuecomment-2478561800.

**Pull request closed without merging**
