### PR TITLE
Add tensorflow compatibility to Python native API

### PR DESCRIPTION
**Pull request by itrushkin**
Jenkins jobs will fail due to test file renaming. I will change them and restart the pipeline manually.

### CODE REVIEW

**Comment by itrushkin** [comment]
Jenkins please retry a build

**Comment by itrushkin** [comment]
Jenkins please retry a build

**Comment by itrushkin** [comment]
Jenkins please retry a build

**Comment by alexey-gruzdev** [comment]
Jenkins please retry a build

**Pull request merged**
