### PR TITLE
Fixes issue #1056 - related to docker src copy permissions in build

### PR DESCRIPTION
**Pull request by ishaileshpant**
- Fix docker permissions issue on src copy command to default user/group

### CODE REVIEW

**Review by teoparvanov — APPROVED** [review]

**Comment by noopurintel** [comment]
@ishaileshpant - Could you also add `name` and `tag` to the generated image - any default value which is agreed upon? Both are `none` right now.

image

**Review by noopurintel — APPROVED** [review]

**Comment by theakshaypant** [comment]
> @ishaileshpant - Could you also add `name` and `tag` to the generated image - any default value which is agreed upon? Both are `none` right now.
> 
> image

@noopurintel the name and tag for the image need to be provided in the docker build command. The [Makefile](https://github.com/securefederatedai/openfl/blob/develop/openfl-docker/Makefile) uses `openfl:latest` (the latest tag is inferred as none is provided in the build command) as the naming convention.

**Comment by noopurintel** [comment]
@teoparvanov - can this be merged now?

**Comment by teoparvanov** [comment]
> @teoparvanov - can this be merged now?

Hi @noopurintel , sure, looks good! Let me merge it for you.

**Pull request merged**
