### PR TITLE
Grpc updated to 1.34.0 and tensorflow to 2.5.0

### LINKED ISSUE #41: Update gRPC for Tensorflow 2.4 compatibility
gRPC is currently pinned to version 1.30. Tensorflow 2.4+ requires a later version. The gRPC version was originally pinned because of sporadic network issues, but this is likely fixed with change to short lived gRPC client connection.

### PR DESCRIPTION
**Pull request by mansishr**
Fixes #41

### CODE REVIEW

**Comment by psfoley** [comment]
Jenkins please retry a build

**Comment by alexey-gruzdev** [comment]
@mansishr let's make a CI green in order to merge it

**Comment by itrushkin** [comment]
There is a bug in tests/github/python_native_tf.py that imports the current TensorFlow version instead of one specified in workspace requirements. To fix it, we need to move `fx.init()` call above `tensorflow.*` imports. 

This bug occurs because our CI containers still have TensorFlow 2.3.1 installed inside. I will bump it ASAP but before that, tests of TensorFlow workspaces will take some time to download `tensorflow==2.5`.

**Comment by itrushkin** [comment]
Jenkins please retry a build

**Pull request merged**
