### PR TITLE
Add flake8 extensions to linter CI workflow

### PR DESCRIPTION
**Pull request by itrushkin**
This pull request contains:
 - Including installation of flake8 extensions
 - Making linter workflow fail on any non-ignored (see setup.cfg) error.
 - Removing linter rules specified directly in workflow code. All rules have already been specified in setup.cfg file in the repository root.
 - Fixing all linter errors 

Tested the behavior locally via [act](https://github.com/nektos/act).

### CODE REVIEW

**Comment by itrushkin** [comment]
New flake8 rules have been applied. I will convert this to a draft and fix all the issues here.

**Review by aleksandr-mokrov — APPROVED** [review]

**Review by igor-davidyuk — COMMENTED** [review]
Great, thank you!
One thing that I would do is separate this into two PRs.
One will contain changes to CI and another one with linter highlited fixes.

**Comment by itrushkin** [comment]
@igor-davidyuk It seems that CI changes affect GitHub actions immediately. I had linter errors after enabling the extensions, thus I had to fix them in the same pull request.

**Comment by igor-davidyuk** [comment]
> @igor-davidyuk It seems that CI changes affect GitHub actions immediately. I had linter errors after enabling the extensions, thus I had to fix them in the same pull request.

Yeah, I thought it was the case. We could Merge a PR with fixes first to avoid this problem 🤣
But this is not that important, one combined PR is ok too.

**Pull request merged**
