### PR TITLE
Docs update

### PR DESCRIPTION
**Pull request by rstoki**
Enhancing documentation:
 - added instruction, how to install `openfl` manually from source on Windows and MacOS (instead of just downloading from central pip repository) 
 -  fixed some "typos" and imperfections

### CODE REVIEW

**Comment by openfl-helper** [comment]
Can one of the admins verify this patch?

**Comment by alexey-gruzdev** [comment]
@rstoki many thanks for contribution, could you please sign a CLA as well?

**Comment by rstoki** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by alexey-gruzdev** [comment]
Jenkins, please retry a build

**Comment by alexey-gruzdev** [comment]
Jenkins please retry a build

**Review by alexey-gruzdev — APPROVED** [review]

**Pull request merged**
