### PR TITLE
Fix Task Runner assignments in Python API

### LINKED ISSUE #27: Same validation metric values across collaborators in Jupyter notebooks
**Describe the bug**
When launching the federated training in Jupyter notebooks of `openfl-tutorials` folder, I noticed that different collaborators achieve the same validation metric values. That could be possible if collaborators had the same data, but the data is randomly split. Looks like there is an issue of defining the Data Loader for each collaborator.

**To Reproduce**
1. Open `openfl-tutorials/Federated_PyTorch_UNET_Tutorial.ipynb` in Jupyter.
2. Execute all cells.

**Expected behavior**
Collaborators have different metrics due to random data split. 

**Screenshot**

image

### PR DESCRIPTION
**Pull request by itrushkin**
Fixes #27.

### CODE REVIEW

**Comment by itrushkin** [comment]
Would it be a better simulation to run collaborators in parallel?

**Comment by alexey-gruzdev** [comment]
Jenkins please retry a build.

**Comment by alexey-gruzdev** [comment]
Jenkins please retry a build

**Comment by itrushkin** [comment]
Multiprocessing in Python native API implies an absence of instances of protobuf classes in parallelized code because forked processes can not pickle such objects. Error:
```
_pickle.PicklingError: Can't pickle <class 'federation_pb2.ModelProto'>: import of module 'federation_pb2' failed
```
@aleksandr-mokrov suggests we will operate with pure Python instances - dictionaries - rather than protobuf-created ones to avoid this issue. This way looks correct to me. I am reworking client-server interaction to use `google.protobuf.json_format.MessageToDict`. Any concerns?

**Comment by alexey-gruzdev** [comment]
@itrushkin let's split this into 2 PRs. Current should be only fixes for #27. And another one for #37.

**Pull request merged**
